[tool.poetry]
name = "svu-industrial-ai"
version = "0.1.0"
description = "It's place for study, research, andgather source together"
authors = ["Augustine77 <hugwolf77@gmail.com>"]
license = "GNU, GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"
pyside6 = "^6.7.0"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
sqlalchemy = "^2.0.30"
requests = "^2.32.2"
pytz = "^2024.1"
numpy = "^1.26.4"
pandas = "^2.2.2"
pydantic = "^2.7.1"
matplotlib = "^3.9.0"
torch = {version = "^2.3.0+cu121", source = "pytorch"}
torchvision = {version = "^0.18.0+cu121", source = "pytorch"}
torchaudio = {version = "^2.3.0+cu121", source = "pytorch"}
scikit-learn = "^1.5.0"

[[tool.poetry.source]]
name = "pytorch"
url = "http://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
